// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N=Integer.parseInt(args[0]);
		int count1=0;
		int count2=0;
		int M=N; // We dont need to define M too, working with N is good enough :)
		while (N!=0){
			double x = Math.random();
			if (x<0.5){
				count1++;
			}
			else{
				count2++;
			}
			N--;
		}
		System.out.println(">0.5: " +count1+ " times");
		System.out.println("<=0.5: " +count2+ " times");
		if (count1!=0 && count2!=0){ // great catching for edge case!
			int max = Math.max(count1,count2);
			int min = M-max;
			double ratio = (double) min/max;
			System.out.println("Ratio: "+ratio);
		}
	}
}

